name: Docker

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: minecraft-saas

jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log into registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build & Push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.ACR_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          secrets: |
            "API_KEY=${{ secrets.API_KEY}}"
            "LOGIN_KEY=${{ secrets.LOGIN_KEY}}"
            "REGISTER_KEY=${{ secrets.REGISTER_KEY}}"
            "CREATE_KEY=${{ secrets.CREATE_KEY}}"
            "GET_KEY=${{ secrets.GET_KEY}}"
            "DELETE_KEY=${{ secrets.DELETE_KEY}}"
  deploy:
    name: Deploy WebApp
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'minecraftsaas'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ secrets.ACR_USERNAME }}/${{ env.IMAGE_NAME }}:latest
